name: ADO Report
on:
  schedule:
  - cron: '0 7 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - run: node ado_report_simple.js "${{ secrets.ADO_PAT }}" "TR-DataAndAnalytics" "Data-Strategy-and-Insights" "Customer Service & Support"
    - uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.office365.com
        server_port: 587
        username: ${{ secrets.OUTLOOK_EMAIL }}
        password: ${{ secrets.OUTLOOK_PASSWORD }}
        from: paula.szczygiel@thomsonreuters.com
        to: paula.szczygiel@thomsonreuters.com
        subject: Azure DevOps Intake Report
        html_body: Report generated
